### ISSUE TITLE
Can`t install

### ISSUE THREAD

**Issue by durnievihor** [MayeoinBread/Blender-IcicleGenerator#1]
I tried to install downloaded .zip, tried to repack it, unpack. nothing worked. Its added to C:Users/name/documents/AppData/Roaming/Blender Foundation/Blender/2.8/scripts/addons/ but it still not working and does not appear in addon window
I`m feeling retard, but i really dont have a clue whats wrong.

**Comment by MayeoinBread** [comment]
Installation issue should be fixed as of commit 48110db
