### ISSUE TITLE
Can't Install on Blender 2.80

### ISSUE THREAD

**Issue by GageRenn** [MayeoinBread/Blender-IcicleGenerator#2]
This add-on can't be installed on Blender 2.80. I would be willing to pay you a fee to take a day or so to update the code to work on Blender 2.90 if you are willing. Just name a price for your time and I'll tell you if I can do it! :)

**Comment by MayeoinBread** [comment]
Apologies for the delay, never got a notification from GitHub!
Will start working on this now, just in time for winter ;)
No payment necessary!

**Comment by MayeoinBread** [comment]
Installation issue should be fixed as of commit 48110db
